// <auto-generated />
using System;
using GNS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225113505_V9")]
    partial class V9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("GNS.Data.Entities.BloomBytesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EmailBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("UserNameBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("BloomBytes");
                });

            modelBuilder.Entity("GNS.Data.Entities.CyberClubEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("CyberClubs");
                });

            modelBuilder.Entity("GNS.Data.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GNS.Data.Entities.GameGamingPlaceEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GamingPlaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "GamingPlaceId");

                    b.HasIndex("GamingPlaceId");

                    b.ToTable("GameGamingPlaces");
                });

            modelBuilder.Entity("GNS.Data.Entities.GamingPlaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CyberClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CyberClubId");

                    b.ToTable("GamingPlaces");
                });

            modelBuilder.Entity("GNS.Data.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GamingPlaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GamingPlaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GNS.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GNS.Data.Entities.WorkingHoursEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CyberClubId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CyberClubId")
                        .IsUnique();

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("GNS.Data.Entities.EmployeeEntity", b =>
                {
                    b.HasBaseType("GNS.Data.Entities.UserEntity");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CyberClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedSecretWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasIndex("CyberClubId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("GNS.Data.Entities.OwnerEntity", b =>
                {
                    b.HasBaseType("GNS.Data.Entities.UserEntity");

                    b.Property<string>("HashedSecretWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Owners", (string)null);
                });

            modelBuilder.Entity("GNS.Data.Entities.CyberClubEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.OwnerEntity", "Owner")
                        .WithMany("CyberClubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GNS.Data.Entities.GameGamingPlaceEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GNS.Data.Entities.GamingPlaceEntity", null)
                        .WithMany()
                        .HasForeignKey("GamingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GNS.Data.Entities.GamingPlaceEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.CyberClubEntity", "CyberClub")
                        .WithMany("GamingPlaces")
                        .HasForeignKey("CyberClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyberClub");
                });

            modelBuilder.Entity("GNS.Data.Entities.OrderEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.GamingPlaceEntity", "GamingPlace")
                        .WithMany("Orders")
                        .HasForeignKey("GamingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GNS.Data.Entities.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("GamingPlace");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNS.Data.Entities.WorkingHoursEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.CyberClubEntity", "CyberClub")
                        .WithOne("WorkingHours")
                        .HasForeignKey("GNS.Data.Entities.WorkingHoursEntity", "CyberClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyberClub");
                });

            modelBuilder.Entity("GNS.Data.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.CyberClubEntity", "CyberClub")
                        .WithMany("Employees")
                        .HasForeignKey("CyberClubId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("GNS.Data.Entities.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("GNS.Data.Entities.EmployeeEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyberClub");
                });

            modelBuilder.Entity("GNS.Data.Entities.OwnerEntity", b =>
                {
                    b.HasOne("GNS.Data.Entities.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("GNS.Data.Entities.OwnerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GNS.Data.Entities.CyberClubEntity", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("GamingPlaces");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("GNS.Data.Entities.GamingPlaceEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GNS.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GNS.Data.Entities.OwnerEntity", b =>
                {
                    b.Navigation("CyberClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
